[package]
name = "project-pingcap-algo"
version = "0.1.0"
authors = ["tyanboot <tyanboot@outlook.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
tempfile = "3.1.0"
serde = { version = "1.0", features = ["derive"] }
clap = "2.33.0"
bincode = "1.1.4"